STATE_DISTRIBUTORS = {
    "AL": {"state": "Alabama", "distributors": ["Brennan Oil Company"]},
    "AK": {"state": "Alaska", "distributors": []},
    "AZ": {"state": "Arizona", "distributors": ["Dennis K Burke Inc"]},
    "AR": {"state": "Arkansas", "distributors": ["Arnold Oil Company"]},
    "CA": {"state": "California", "distributors": ["Dennis K Burke Inc"]},
    "CO": {"state": "Colorado", "distributors": ["Avery Oil Company"]},
    "CT": {"state": "Connecticut", "distributors": ["Dennis K Burke Inc"]},
    "DE": {"state": "Delaware", "distributors": ["American Lube Supply (HJDJ)"]},
    "FL": {"state": "Florida", "distributors": ["Brennan Oil Company"]},
    "GA": {"state": "Georgia", "distributors": ["Brennan Oil Company"]},
    "HI": {"state": "Hawaii", "distributors": []},
    "ID": {"state": "Idaho", "distributors": ["Avery Oil Company"]},
    "IL": {"state": "Illinois", "distributors": ["American Lube Supply (HJDJ)"]},
    "IN": {"state": "Indiana", "distributors": ["American Lube Supply (HJDJ)"]},
    "IA": {"state": "Iowa", "distributors": ["Avery Oil Company"]},
    "KS": {"state": "Kansas", "distributors": ["Avery Oil Company"]},
    "KY": {"state": "Kentucky", "distributors": ["Brennan Oil Company"]},
    "LA": {"state": "Louisiana", "distributors": ["Arnold Oil Company"]},
    "ME": {"state": "Maine", "distributors": ["Dennis K Burke Inc"]},
    "MD": {"state": "Maryland", "distributors": ["American Lube Supply (HJDJ)"]},
    "MA": {"state": "Massachusetts", "distributors": ["Dennis K Burke Inc"]},
    "MI": {"state": "Michigan", "distributors": ["American Lube Supply (HJDJ)"]},
    "MN": {"state": "Minnesota", "distributors": ["Avery Oil Company"]},
    "MS": {"state": "Mississippi", "distributors": ["Arnold Oil Company"]},
    "MO": {"state": "Missouri", "distributors": ["Avery Oil Company"]},
    "MT": {"state": "Montana", "distributors": ["Avery Oil Company"]},
    "NE": {"state": "Nebraska", "distributors": ["Avery Oil Company"]},
    "NV": {"state": "Nevada", "distributors": ["Dennis K Burke Inc"]},
    "NH": {"state": "New Hampshire", "distributors": ["Dennis K Burke Inc"]},
    "NJ": {"state": "New Jersey", "distributors": ["American Lube Supply (HJDJ)"]},
    "NM": {"state": "New Mexico", "distributors": ["Avery Oil Company"]},
    "NY": {"state": "New York", "distributors": ["Dennis K Burke Inc"]},
    "NC": {"state": "North Carolina", "distributors": ["Brennan Oil Company"]},
    "ND": {"state": "North Dakota", "distributors": ["Avery Oil Company"]},
    "OH": {"state": "Ohio", "distributors": ["American Lube Supply (HJDJ)"]},
    "OK": {"state": "Oklahoma", "distributors": ["Arnold Oil Company"]},
    "OR": {"state": "Oregon", "distributors": ["Dennis K Burke Inc"]},
    "PA": {"state": "Pennsylvania", "distributors": ["American Lube Supply (HJDJ)"]},
    "RI": {"state": "Rhode Island", "distributors": ["Dennis K Burke Inc"]},
    "SC": {"state": "South Carolina", "distributors": ["Brennan Oil Company"]},
    "SD": {"state": "South Dakota", "distributors": ["Avery Oil Company"]},
    "TN": {"state": "Tennessee", "distributors": ["Brennan Oil Company"]},
    "TX": {"state": "Texas", "distributors": ["Texas Enterprises Inc", "American Lube Supply (HJDJ)", "Avery Oil Company", "Arnold Oil Company"]},
    "UT": {"state": "Utah", "distributors": ["Avery Oil Company"]},
    "VT": {"state": "Vermont", "distributors": ["Dennis K Burke Inc"]},
    "VA": {"state": "Virginia", "distributors": ["Brennan Oil Company"]},
    "WA": {"state": "Washington", "distributors": ["Dennis K Burke Inc"]},
    "WV": {"state": "West Virginia", "distributors": ["Brennan Oil Company"]},
    "WI": {"state": "Wisconsin", "distributors": ["American Lube Supply (HJDJ)"]},
    "WY": {"state": "Wyoming", "distributors": ["Avery Oil Company"]},
    "DC": {"state": "District of Columbia", "distributors": ["American Lube Supply (HJDJ)"]},
}

DISTRIBUTOR_COLORS = {
    "Texas Enterprises Inc": "#228B22",
    "American Lube Supply (HJDJ)": "#4169E1",
    "Avery Oil Company": "#FF8C69",
    "Arnold Oil Company": "#C0C0C0",
    "Dennis K Burke Inc": "#DAA520",
    "Brennan Oil Company": "#DC143C",
}

ALL_DISTRIBUTORS = sorted(DISTRIBUTOR_COLORS.keys())
